### ISSUE TITLE
Getting a 502 error when installing

### ISSUE THREAD

**Issue by chrisshattuck** [kalamuna/kalaboxv1#23] opened 2014-06-23 20:06 UTC
I didn't dig in to figure out if this is an easily correctable issue, but after installation, I got a 502 error (I think it was in an overlay), and then after spinning up a site or going to what I assume would be PHPMyAdmin, I get a 502 there as well. I'm on a Mac, OSX v.10.9.2.

**Comment by pirog** [comment] 2014-06-24 19:19
@chrisshattuck can you post a screenshot? Is there an error message at all?

**Comment by ari-gold** [comment] 2014-06-24 23:22
I just had to reinstall Kalabox as I got my Macbook wiped at Apple store and I'm experiencing the same problem.

After install I get the error "Error
There's a problem with loading your sites list. Restarting the box may resolve it."

and in ~/.kalabox/kalabox.log I see

2014-06-24T23:18:53.129Z - info: Installation completed successfully.
2014-06-24T23:18:54.004Z - warn: Error retrieving sites list: SyntaxError: Unexpected token <

Visiting php.kala or start.kala yield "502 Bad Gateway
nginx/1.1.19"

**Comment by pirog** [comment] 2014-06-25 01:16
Hey guys, i'd def check this related issue and also this to see if it resolves your problem. Slight diff in new php versions may be the culprit
http://www.nginxtips.com/php5-fpm-sock-failed-13-permission-denied-error/

**Comment by ari-gold** [comment] 2014-06-25 16:22
Thanks for tracking this down! That does appear to be the issue.

First I got start.kala up by editing  /etc/php5/fpm/pool.d/www.conf

;listen = /tmp/php-fpm.sock
 listen = 127.0.0.1:9000

and /etc/nginx/sites-enabled/start

 fastcgi_pass 127.0.0.1:9000;
 #fastcgi_pass unix:/tmp/php-fpm.sock;

And restarting nginx and php5-fpm

This would require changing all vhosts in sites-enabled.

So I looked at the link you posted and restored the files I edited above to their original state and edited /etc/php5/fpm/pool.d/www.conf and changed 

;listen.owner = vagrant
 ;listen.group = vagrant

to

listen.owner = vagrant 
listen.group = vagrant

Now start.kala, aliases.kala, php.kala all come up as "Welcome to nginx!"

**Comment by pirog** [comment] 2014-06-25 19:28
@ari-gold solid!

That makes sense. You _may_ need to specify different ports for each vhost so 9001 for start.kala, 9002 for php.kala, etc

That all said, I think we want to roll with a socket instead of tcp for our use case. I suspect there was a change in the default php version that ships with 12.04 which is causing our config to fail. We will want to make sure the socket which is in /tmp has the correct permissions and ownership and that should fix the issue. It's probably being set as root and it needs to be nginx or some such. 

TO ALL THE OTHER READERS OUT THERE. This is also a great use case for why Kalabox v2 is worth supporting. These kinds of issues with config updating won't be a problem because the state of the docker container will be the same.

**Comment by pirog** [comment] 2014-06-25 19:29
@reynoldsalec i am pretty sure this is blowing up all new box installs we will want to roll out a new release ASAP.

**Comment by pirog** [comment] 2014-06-25 19:48
So this is actually an underlying issue with Kalastack and i can confirm it is an issue.
https://github.com/kalamuna/kalastack/issues/85

**Comment by pirog** [comment] 2014-06-25 19:51
The easiest fix for this as of right now is to SSH into the box or stack and run 

```
$ sudo chown vagrant:vagrant /tmp/php-fpm.sock
```

**Comment by pirog** [comment] 2014-06-25 20:04
@reynoldsalec, fix has been posted in Kalastack but we need to roll a new release of Kalabox to pull it in
https://github.com/kalamuna/kalastack/commit/410a5ad7811c9fe70905e8d0417269fee92ab83c

**Comment by reynoldsalec** [comment] 2014-06-25 20:30
Awesome, @pirog let's look at rolling a new release this evening, we can document that procedure then.

**Comment by pirog** [comment] 2014-06-25 20:31
Perfect! That sounds great to me.

On Wed, Jun 25, 2014 at 1:30 PM, reynoldsalec notifications@github.com
wrote:

> Awesome, @pirog https://github.com/pirog let's look at rolling a new
> release this evening, we can document that procedure then.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalabox/issues/23#issuecomment-47154462.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by pirog** [comment] 2014-06-26 05:10
This fix will be in the latest (and first open source) release

**Closed as completed by pirog** 2014-06-26 05:10 UTC
